#+TITLE: Chapter 16: Rough Guide to Continuous Time

This chapter briefly introduces Brownian motion as the limit of the
binomial tree, shows how we can use Ito's lemma to tackle the change
of numeraire and risk-neutral distributions in continuous time,
arriving at the Black-Scholes formula.

* 16.1 Brownian Motion as Random Walk Limit

Let $\xi_i$ be IID and equal to $\pm 1$ with probability 1/2 and consider the symmetric random walk $\Sigma_{i=1}^N \xi_i$

By the central limit theorem

$W_N = \Sigma_{i = 1}^N \frac{1}{\sqrt{N}} \to W$ as $N \to \infty$, where $W \sim \mathcal{N}(0, 1)$

For fixed $t>0$, we can define:

$W_{N,t} = \Sigma_{i = 1}^{[Nt]} \frac{1}{\sqrt{N}} = \sqrt{t}\Sigma_{i=1}^{[Nt]}\frac{1}{\sqrt{Nt}}\xi_i$

where $[Nt]$ is the closest integer to $Nt$. Then

$W_{N, t} \to W_t \sim \mathcal{N}(0, t)$ as $N \to \infty$

The limit $W_t$, the continuous-time limit of a symmetric random walk,
is called *Brownian Motion* or a *Wiener Process*.  It has the following
properties:

a. $W_0 = 0$
b. For all $t \leq s$, $W_s - W_t \sim \mathcal{N}(0, s - t)$
c. $W_s - W_t$ is independent of $W_t, t \leq s$

Intuitively, we can understand Brownian motion as the limit of the
symmetric random walk with ever smaller time steps.  Equivalently, we
can think of it as a process with independent normal increments, since
for any $t, \Delta t > 0$

$W_{t + \Delta t} - W_t \sim \mathcal{N}(0, \Delta t)$

Note that Brownian motion is a Martingale.

* 16.2 Stochastic Differential Equations and Geometric Brownian Motion

For $\Delta t > 0$, we can write a difference equation such as

$S_{t + \Delta t} - S_t = \mu \Delta t + \sigma (W_{t + \Delta t} - W_t) = \mu \Delta t + \sigma \sqrt{\Delta t} W$, $W \sim \mathcal{N}(0, 1)$

We write the limits as $\Delta t \to 0$:

$dS_t = \mu dt + \sigma d W_t$

or more generally

$dS_t = \mu(S_t, t)dt + \sigma(S_t, t) d W_t$

This is a *stochastic differential equation*.

The meaning of $dW_t$ is non-trivial, although the discrete analogue
$\sqrt{\Delta t}W$ where $W \sim \mathcal{N}(0, 1)$ is helpful for
conceptual understanding.

A reasonable choice of functions $\mu(S_t, t), \sigma(S_t, t)$ to model the behavior of a stock price is to:

- assume that the drift $\mu$ of a stock is proportional to its price, $\mu(S_t, t) = \mu S_t$
  - with no random term, the ODE would be $dS_t = \mu S_tdt \implies S_t = S_0e^{\mu t}$

- For $\sigma(S_t, t)$, we might assume that the uncertainty about the stock's percentage return is constant

  - i.e. $p(S_t) = 100 \to \not \in (99, 101) \equiv p(S_t) = 50 \to \not \in (49.5, 50.5)$

  - Then over small $\Delta t$, $\mathrm{Var}(\frac{\Delta S_t}{S_t}) \approx \sigma^2 \Delta t \implies \mathrm{Var}(\Delta S_t) \approx \sigma^2 S_t^2 \Delta t$

Therefore, one possible process for the evolution of the stock is

$dS_t = \mu S_t dt + \sigma S_t d W_t$

which is the definition that the stock follows *geometric Brownian motion*.

The discrete time analogue is

$\frac{\Delta S_t}{S_t} = \mu \Delta t + \sigma \sqrt{\Delta t} W$ where $W \sim \mathcal{N}(0, 1)$

* 16.3 Ito's Lemma

Consider a function $f(X_t, t)$ of $X_t$.

For non-random $X_t$

$df = \frac{\delta f}{\delta t}dt + \frac{\delta f}{\delta X_t} dX_t$

by the chain rule for differentiation. Now suppose that

$\Delta X_t = \mu \Delta t + \sigma \sqrt{\Delta t} W$, $W \sim \mathcal{N}(0, 1)$

Then

$(\Delta X_t)^2 = \sigma^2 \Delta t W^2 + O(\Delta t^{\frac{3}{2}})$

Since $E(W^2) = 1$ and $\mathrm{Var}(W^2) = 2$, then $(\Delta X_t)^2 \to \sigma^2 \Delta t$ as $\Delta t \to 0$ and we have

$\Delta f \approx \frac{\delta f}{\delta t}\Delta t + \frac{\delta f}{\delta X_t}\Delta X_t + \frac{1}{2} \frac{\delta^2 f}{\delta^2 X_t^2} \sigma^2 \Delta t$

Taking limits we obtain *Ito's Lemma*:

If $dx = \mu dt + \sigma dW_t$, then

$df = \frac{df}{dt}dt + \frac{df}{dx}dx + \frac{1}{2}\frac{d^2f}{dx^2} dx^2 = (\frac{\partial f}{\partial t} + \frac{\partial f}{\partial X_t} \mu(X_t, t) + \frac{1}{2} \frac{\partial^2 f}{\partial X_t^2} \sigma^2(X_t, t))dt + \frac{\partial f}{\partial x_t} \sigma(X_t, t) dW_t$


Ito's Lemma is easiest to remember in the following form: If $dx = \mu dt + \sigma d W_t$ then

$df = \frac{df}{dt}dt + \frac{df}{dx}dx + \frac{1}{2}\frac{d^2f}{dx^2} dx^2$

where $dx^2$ is defined by the identities $dt^2 = 0, dtdW_t = 0, (dW_t)^2 = dt$

Applying Ito's lemma to $\log S_t$ where $S_t$ follows geometric Brownian motion:

Let $f(S_t) = \log S_t$. Then

$\frac{\partial f}{\partial t} = 0$

$\frac{\partial f}{\partial S_t} = \frac{1}{S_t}$

$\frac{\partial^2f}{\partial S_t^2} = -\frac{1}{S_t^2}$

Ito's lemma gives

$d(\log S_t) = (\frac{1}{S_t}\mu S_t - \frac{1}{2} \sigma^2 S_t^2 \frac{1}{S_t^2}) dt + \sigma S_t \frac{1}{S_t}d W_t = (\mu - \frac{1}{2}\sigma^2)dt + \sigma dW_t$

Therefore, $\log S_t$ follows standard Brownian motion and is normally distributed. Specifically,

$\log S_T | S_t \sim \mathcal{N}(\log S_t + (\mu - \frac{1}{2}\sigma^2)(T - t), \sigma^2(T - t))$

showing that under geometric Brownian motion the distribution of $\log
S_T | S_t$
is lognormal, equal to the limiting distribution of the binomial tree.

* 16.4 Black-Scholes Equation

Now let our function be the price of a call (or other derivative)
$C_K(t, T)$, which is a function of the underlying stock price. If the
stock follows geometric Brownian motion, then by Ito's lemma, the
option price satisfies the stochastic differential equation:

$dC_K(t, T) = (\frac{\partial C_K(t, T)}{\partial t} + \frac{\partial C_K(t, T)}{\partial S_T} \mu S_t + \frac{1}{2}\frac{\partial^2 C_K(t, T)}{\partial S_t^2} \sigma^2 S_t^2)dt + \frac{\partial C_K(t, T)}{\partial S_t}\sigma S_t dW_t$

Suppose we construct at t a portfolio $\Pi$ consisting of long one
option and short $\frac{\partial C_K(t, T)}{\partial S_t}$ of
stock. Its price $\Pi_t$ at time t satisfies

$\Pi_t = C_K(t, T) - \frac{\partial C_K(t, T)}{\partial S_t}S_t$

Using our expressions for $dC_K$ and $dS_t$, we obtain

$d \Pi_t = (\frac{\partial}{\partial t}C_k(t, T) + \frac{1}{2}\frac{\partial^2 C_K(t, T)}{\partial S_t^2}\sigma^2 S_t^2) dt$

This portfolio instantaneously at t has no exposure to the term
$dW_t$. Therefore, it is instantaneously a replicating portfolio for
the money market account and must grow at rate $r$. So

$d \Pi_t = r \Pi_t dt \implies \frac{\partial}{\partial t}C_k(t, T) + \frac{1}{2}\frac{\partial^2 C_K(t, T)}{\partial S_t^2}\sigma^2 S_t^2 = r (C_K(t, T) - \frac{\partial C_K(t, T)}{\partial S_t}S_t)$

Therefore, we obtain

$\frac{\partial}{\partial t}C_k(t, T) + \frac{1}{2}\frac{\partial^2 C_K(t, T)}{\partial S_t^2}\sigma^2 S_t^2 -  r (C_K(t, T) + r \frac{\partial C_K(t, T)}{\partial S_t}S_t = 0$

which is the *Black-Scholes partial differential equation* for a
European derivative contract. The solution to this PDE, under the
boundary conditions $C_K(T, T) = (S_T - K)^+$ is the Black-Scholes
formula we derived probabilistically in chapter 10.

* 16.5 Ito and Change of Numeraire

Consider two processes $X_t, Y_t$ s.t.

$dX_t = \mu(X_t, t)dt + \sigma(X_t, t) dW_t$

$dY_t = \mu(Y_t, t)dt + \sigma(Y_t, t) dW_t$

Then $f(X_t, Y_t, t)$ satisfies the stochastic differential equation

$df = \frac{\partial f}{\partial t}dt +
\frac{\partial f}{\partial X_t}dX_t +
\frac{\partial f}{\partial Y_t}dY_t +
\frac{1}{2}\frac{\partial^2 f}{\partial X_t^2}dX_t^2 +
\frac{\partial^2 f}{\partial X_tY_t}dX_tY_t +
\frac{1}{2}\frac{\partial^2 f}{\partial Y_t^2}dY_t^2$

setting $f(x, y) = xy$, we obtain

$d(X_tY_t) = X_tdY_t + Y_tdX_t + dX_tdY_t$

which is a useful result when considering the ratio of an asset to a numeraire.

Suppose that $S_t$ follows geometric Brownian motion $dS_t = \mu S_t
dt + \sigma S_t dW_t$.
The money market account $M_t = e^{rt}$ satisfies $dM_t = rM_t dt$, and so

$d(\frac{1}{M_t}) = -\frac{1}{M_t^2}dM_t = -\frac{r}{M_t}dt$

We can now apply Ito's lemma to the ratio $S_t/M_t$:

$d(\frac{S_t}{M_t}) = (\mu - r)\frac{S_t}{M_t} + \sigma \frac{S_t}{M_t} dW_t$

Thus $S_t/M_t$ follows geometric Brownian motion, and we have

$\log(\frac{S_t}{M_t} | S_t) \sim \mathcal{N}(\log(\frac{S_t}{M_t}) + (\mu - r)(T - t) - \frac{1}{2}\sigma^2(T - t), \sigma \sqrt{T - t})$

As an example, let $f(S_t) = F(t, T) = S_t e^{r(T - t)}$, the forward
price at time t. Then we have:

$\frac{\partial f}{\partial t} = -rS_te^{r(T - t)}$ and $\frac{\partial f}{\partial S_t} = e^{r(T - t)}$

and Ito's lemma gives us the following stochastic differential
equation for the forward price:

$dF(t, T) = (\mu - r)F(t, T)dt + \sigma F(t, T)dW_t$

In the risk-neutral world, $\mu = r$ and we have

$dF(t, T) = \sigma F(t, T)dW_t$

Therefore,

$\log F(T^*, T) | F(t, T) \sim \mathcal{N}(\log F(t, T) - \frac{1}{2}\sigma^2(T^* - t), \sigma^2(T^* - t))$

and

$E(F(T^*, T) | F(t, T)) = F(t, T)$

for $t \leq T^* \leq T$. This shows that the forward price is a
martingale under the risk-neutral distribution. This was shown
earlier: we know from the fundamental theorem that we must have this
result, since the forward price is itself the ratio of the stock to
the ZCB.

#+begin_quote
We can begin to see the formation of a continuous-time analogue of our
work on numeraires, martingales and the fundamental theorem.

First we choose an appropriate numeraire, often chosen to simplify
calculation.

Given the stochastic differential equation for the underlying asset,
we calculate using Ito’s lemma the stochastic differential equation
for assets rebased by that numeraire.

By the fundamental theorem, the absence of arbitrage is equivalent to
the rebased assets being martingales, which is itself equivalent to
the stochastic differential equation having zero drift.

We can thus determine the risk-neutral distribution with respect to
the numeraire by imposing this condition.
#+end_quote

Delightful

There is another example in the book of a change of numeraire, in
which he sets the stock price $S_t$ as the numeraire and calculates $d(\frac{M_t}{S_t})$

The change of numeraire machinery above is a powerful tool in finance,
and we can immediately apply it to the /Black-Scholes Formula/.

We can split the payout $(S_T - K)^+ = (S_T - K) I\{S_T \geq K\}$ into
2 parts:

*A*. $S_T I\{S_T \geq K\}$
*B*. $-KI\{S_T \geq K\}$

To price *A*, let the price at time t be denoted $D^A(t, T)$ and the
payout at time T be denoted $D^A(T, T) = S_T I\{S_T \geq K\}$. By
the fundamental theorem:

$\frac{D^A(t, T)}{S_t} = P^{**}(S_T \geq K | S_t)$

where $P^{**}$ is the risk-neutral distribution with respect to the
stock numeraire. Therefore,


$D^A(t, T) = S_t P^{**}(S_T \geq K | S_t)$

Under the risk-neutral distribution with respect to the stock
numeraire, we set $\mu = r + \sigma^2$ and

$\log S_T | S_t \sim \mathcal{N}(\log S_t + (r + \frac{1}{2} \sigma^2)(T - t), \sigma^2(T - t))$

Therefore,

$P^{**}(S_T \geq K | S_t) = \Phi(\frac{\log (\frac{S_t}{K}) + (r + \frac{\sigma^2}{2})(T - t)}{\sigma \sqrt{T - t}})$

For *B*, we use the money market account as the numeraire, and consider
the derivative with payout at time T $D^B(T, T) = KI\{S_T \geq K\}$.
By the fundamental theorem:

$\frac{D^B(t, T)}{M_t} = Ke^{-rT}P^*(S_T \geq K | S_t)$

Under $P^*$, the risk-neutral distribution w.r.t the money market
account, we set $\mu = r$, and so

$\log S_T | S_t \sim \mathcal{N}(\log S_t + (r - \frac{1}{2}\sigma^2)(T - t), \sigma^2(T - t))$

Combining *A* and *B* we obtain the *Black-Scholes formula*:

*A*. $S_T I\{S_T \geq K\}$
*B*. $-KI\{S_T \geq K\}$

$C_K(t, T) = S_t \Phi(\frac{\log (\frac{S_t}{K}) + (r + \frac{\sigma^2}{2})(T - t)}{\sigma \sqrt{T - t}}) - Ke^{-r(T - t)} \Phi(\frac{\log (\frac{S_t}{K}) + (r + \frac{\sigma^2}{2})(T - t)}{\sigma \sqrt{T - t}} - \sigma \sqrt{T - t})$
