#+TITLE: Chapter 2: Forward Contracts and Forward Prices

A *derivative contract*, or simply *derivative*, is a financial contract between 2 counterparties whose value is a function of - derives from, hence derivative - the values of another variable, for example the price of a security such as a stock. In this book, we will exclusively consider *financial derivatives*, derivatives of financial assets like stocks or variables like interest rates.

Derivatives traded directly between two counterparties are called *over-the-counter (OTC)* derivatives. OTC derivatives contrast with *exchange-traded* derivatives, where an exchange matches buyers and sellers and each counterparty faces the exchange on the contract.

* 2.2 Forward Contracts

A *forward contract*, or simply *forward*, is an agreement between two counterparties to trade a specific asset, for example a stock, at a certain future time $T$ and at a certain price $K$.
At the current time $t \leq T$, one counterparty agrees to buy the asset at $T$, and is *long* the forward contract. The other counterparty agrees to sell the asset, and is *short* the forward contract. The specified price $K$ is known as the *delivery price*. The specified time $T$ is known as the *maturity*.

We define $V_K(t, T)$ to be the *value* at the current time $t \leq T$ of being long a forward contract with delivery price $K$ and maturity $T$, that is, how much the contract itself is worth at time $t$ to the counterparty which is long.

Since the counterparty long the forward contract must pay $K$ at $T$ to buy an asset which is worth $S_T$, we immediately have $V_K(T, T) = S_T - K$. Similarly, the payout at maturity from a short forward contract is $K - S_T$.

We define the *forward price* $F(t, T)$ at current time $t \leq T$ to be the delivery price $K$ such that $V_K(t, T) = 0$. That is, such that the forward contract has 0 value at time $t$.

Suppose a stock which pays no dividends always has price 100 and interest rates are always 0. Then we should convince ourselves that $F(t, T) = 100$ and $V_K(t, T) = 100 - K$ for all $t \leq T$.

* 2.3 Forward on Asset Paying No Income

Let $r$ be the constant zero rate with continuous compounding, and for now suppress any dependence of the interest rate on time.

** Result:

For an asset paying no income, for example a stock that pays no dividends,

$F(t, T) = S_t e^{r(T - t)}$

when $t = 0$, we have the simple expression

$F(0, T) = S_0 e^{rT}$

* 2.4 Forward on Asset Paying Known Income

** Result Forward on Assets paying known income

Suppose an asset pays a known amount of income (for example, dividends, coupons, or even rent) during the life of the forward contract, and the present value at $t$ of the income is $I$. Then

$F(t, T) = (S_t - I)e^{r(T - t)}$

* 2.5 Review of Assumptions

1. We can borrow or lend money freely at rate $r$
2. We can always buy or sell as much of the asset as we want, and the market is sufficiently deep that the amount we buy or sell does not move the price
3. We can *sell assets short* at will, that is, have negative amounts of assets we do not own
4. People always want to exploit arbitrages in order to obtain "free money", and have the capacity to do so.

These are all violatable in certain conditions

* 2.6 Value of Forward Contract

** Result Value of a Forward Contract on an Asset paying no known income

The value of the forward contract on an asset satisfies

$V_K (t, T) = (F(t, T) - K)e^{-r(T - t)}$

* 2.7 Forward on Stock Paying Dividends and on Currency

** Result

Suppose a stock pays dividends at a known dividend yield $q$, expressed as a percentage of the stock price on a continually compounded per annum basis. Then the forward price satisfies

$F(t, T) = S_t e^{(r - q)(T - t)}$

Simular to the example where the asset pays a known income, the presence of dividends lowers the forward price. There is an advantage to buying the asset spot versus buying it forward, since in the latter case we do not receive any dividends paid before $T$. The forward price is lower in order to compensate. The forward contract on a foreign currency is similar.

** Result

Suppose $X_t$ is the price at time $t$ in dollars of one unit of foreign currency. Let $r_d$ be the dollar zero rate and $r_f$ the foreign zero rate, both constant and continually compounded. Then the forward price satisfies

$F(t, T) = X_t e^{(r_d - r_f)(T - t)}$

* 2.8 Physical vs. Cash Settlement

We have assumed that forwards are *physically settled*, meaning that one actually pays $K$ and receives the asset at time $T$. However, some forwards are *cash settled*, meaning one simply receives (pays if negative) the amount $S_T - K$ at $T$.

Cash settled contracts are also sometimes known as *contracts for difference*. Both have the same value at $T$, and hence for $t \leq T$. However, a cash settled forward has no further exposure to the asset price, whilst a physically settled contract -- where one owns the asset at $T$ -- continues to have exposure after $T$.

Cash-settled forwards have many similarities with *spread bets*. For example, if one were to buy Boston Red Sox wins at 90, in size one dollar per win, one would have a long forward position with a delivery price 90. If the Red Sox win 100 games, the better would make $10, whereas if they win 81 games, the better loses $9. The payout is $S_T - K$, where $S_T$ is the number of wins.

A key difference is that $S_T$ is not the price of a security or tradable asset and so the replication and no-arbitrage arguments for forward pricing do not apply.

* 2.9 Summary

| Underlying                         | Forward Price                |
|------------------------------------+------------------------------|
| Asset paying no income             | $S_t e^{r(T - t)}$           |
| Asset paying known income $I$      | $(S_t - I)e^{r(T - t)}$      |
| Asset paying dividends at rate $q$ | $S_t e^{(r - q)(T - t)}$     |
| Foreign Exchange                   | $X_t e^{(r_d - r_f)(T - t)}$ |
