#+TITLE: Chapter 7: Options

* 7.1 Option Definitions

A *European call option* with *strike* or *exercise price* $K$ and *exercise date* or *maturity* $T$ on an asset is the right -- but not the obligation -- to buy the assest for $K$ at time $T$. The execution of this right is termed the *exercise* of the option.

The payout $g(S_T) = \max{(S_T - K, 0)} = (S_T - K)^+$

A *European put option* is the right to sell the asset for $K$ at time $T$.

The payout of a put option at time $T$ is $\max{(K - S_T, 0)} = (K - S_T)^+$

A *straddle* is a call plus a put of the same strike and maturity, and has payout $|S_T - K|$.

- A *European* option allows exercise only at time $T$
  - these are common on forward-rate agreements, and known as caps and floors
- An *American* option allows exercise at any time $t \leq T$
  - these are common on stocks
- A *Bermudan* option allows exercise at a finite set of times $T_0, ..., T_n \leq T$
  - these are common on swaps, where they underlie mortgages and callable bonds

At time t, a call option with strike K at maturity T is said to be:

- *at-the-money* if $S_t = K$
- *in-the-money* if $S_t > K$
- *out-of-the-money* is $S_t < K$

At time $t \leq T$, a call option is struck:

- *at-the-money-forward (ATMF)* if $K = F(t, T)$
- *in-the-money-forward* if $K < F(t, T)$
- *out-of-the-money-forward* if $K > F(t, T)$

The *intrinsic value* of an option is its payout were we able to exercise it now. Thus, the intrinsic value of a call is $\max\{S_t - K, 0\}$, and of a put is $\max\{K - S_t, 0\}$.

* 7.2 Put-Call Parity

Let $C_K(t, T)$ be the price at time $t$ of the European call, and $P_K(t, T)$ be the price of the European put, with strike price $K$ at maturity $T$.

** Result

$C_K(t, T) \geq 0$ and $P_K(t, T) \geq 0$

** Result : Put-Call Parity

Put-Call parity relates the prices of the call and put of the same strike with the value of the forward.

$C_K(t, T) - P_K(t, T) = V_K(t, T)$

where $V_K(t, T)$ is the value at time $t$ of the forward contract with delivery price $K$, i.e. $V_K(t, T) = (F(t, T) - K)Z(t, T)$

for ATMF options, put-call parity becomes

$C_{F(t, T)}(t, T) - P_{F(t, T)}(t, T) = 0$

That is, the price of an ATMF put equals that of an ATMF call. This result is independent of any distributional assumptions and holds regardless of whether $S_T$ is skewed to the left or right, or has any other unusual distributional features.

* 7.3 Bounds on Call Prices

** Result

The European call price on a non-dividend paying stock satisfies

$\max\{0, S_t - KZ(t, T)\} \leq C_K(t, T) \leq S_t$

** Corollary

The price of an American call and European call on a non-dividend-paying stock are equal

* 7.4 Call and Put Spreads

A *call spread* is a portfolio consisting of long one call option with strike $K_1$ and short one call option with strike $K_2$, both with maturity $T$, where $K_1 < K_2$.

A call spread has value $C_{K_1}(t, T) - C_{K_2}(t, T)$ at time $t$. At time $T$ its payout equals

- 0 if $S_T \leq K_1$
- $S_T - K_1$ if $K_1 \leq S_T \leq K_2$
- $K_2 - K_1$ if $S_T \geq K_2$

** Result

If $K_1 < K_2$, then $C_{K_1}(t, T) \geq C_{K_2}(t, T)$ and $P_{K_1}(t, T) \leq P_{K_2}(t, T)$

In particular, the call spread and put spread have non-negative value for all $t \leq T$

** Result

If $K_1 < K_2$, then

$C_{K_1}(t, T) - C_{K_2}(t, T) \leq Z(t, T)(K_2 - K_1)$

and

$P_{K_2}(t, T) - P_{K_1}(t, T) \leq Z(t, T)(K_2 - K_1)$

** Result

Combining the two previous results, we have

$C_{K_2}(t, T) \leq C_{K_1}(t, T) \leq C_{K_2}(t, T) + Z(t, T)(K_2 - K_1)$

* 7.5 Butterflies and Convexity of Option Prices

** Result

Let $K_1 < K_2$, $\lambda \in (0, 1)$ and let $K^* = \lambda K_1 + (1 - \lambda) K_2$. Then we have

$C_{K^*}(t, T) \leq \lambda C_{K_1}(t, T) + (1 - \lambda)C_{K_2}(t, T)$

In other words, $C_K(t, T)$ is a convex function of $K$.

A portfolio of this form (or multiples of it) is called a *call butterfly*.

* 7.6 Digital Options

A *digital call option* with strike $K$ and maturity $T$ has payout at $T$

- 1 if $S_T \geq K$
- 0 if $S_T < K$

A *digital put option* with strike $K$ and maturity $T$ pays


- 1 if $S_T \leq K$
- 0 if $S_T > K$

* 7.7 Options on Forward Contracts

Let $C^{F_K}(t, T)$ be the price of a European call option with exercise date $T$ on a forward contract, specifically the right to enter at time $T$ (at 0 cost) into a long forward contract with delivery price $K$ at maturity $T$.


** Result

The price of an American put on a forward contract equals the price of a European put, that is

$\tilde{P}^{F_K}(t, T) = P^{F_K}(t, T) = P_K(t, T)$

Therefore we have $\tilde{P}^{F_K}(t, T) \leq \tilde{P}_K(t, T)$

Similarly,

$\tilde{C}^{F_K}(t, T) = C^{F_K}(t, T) = C_K(t, T)$

The right to pay $K^*$ at $T$ to enter into a forward contract, with delivery price $K$ and maturity $T$, is the same as the right to pay $K + K^*$ to buy the stock at $T$.
